# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 量子アニーリングナレッジベース T-Wave
author: 東北大学量子アニーリング研究開発室 T-QARD
copyright: "2021"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'
  
only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: t-wave.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year

# Information about where the book exists on the web
repository:
  url: https://github.com/t-qard/t-wave  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: false

# Information about where the book exists on the web
repository:
  url                       : https://github.com/t-qard/t-wave  # Online location of your book
  path_to_book              : ""  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org"
